config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :accounts
  resources :categories
  resources :transactions
  resources :goals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transaction, only: %i[show edit update destroy]
  before_action :load_accounts, only: :index
  before_action :load_categories, only: :index

  def index
    @q = Transaction.ransack(params[:q])
    @transactions = Transactions::SearchService.new(params: params[:q], user: current_user).call
  end

  def show; end

  def new
    @transaction = Transaction.new(
      account_id: params[:account_id],
      transaction_type: params[:transaction_type]
    )
  end

  def edit; end

  def create
    @transaction = Transaction.new(transaction_params)

    unless valid_account?(@transaction.account)
      @transaction.errors.add(:account, t("transactions.errors.invalid"))
      return render :new, status: :unprocessable_entity
    end

    if transaction_processor.process_transaction(:save!)
      redirect_to transactions_path, notice: t("transactions.notice.create")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @transaction.assign_attributes(transaction_params)

    unless valid_account?(@transaction.account)
      @transaction.errors.add(:account, t("transactions.errors.invalid"))
      return render :edit, status: :unprocessable_entity
    end

    if transaction_processor.process_transaction(:save!)
      redirect_to transactions_path, notice: t("transactions.notice.edit")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    ActiveRecord::Base.transaction do
      @transaction.destroy!
      Accounts::UpdateBalanceService.new(@transaction.account).call
    end
    redirect_to transactions_url, notice: t("transactions.notice.destroy")
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(
      :amount, :transaction_type, :description,
      :due_date, :status, :account_id, :category_id,
      :voucher
    )
  end

  def valid_account?(account)
    account && current_user.accounts.ids.include?(account.id)
  end

  def load_accounts
    @accounts = current_user.accounts
  end

  def load_categories
    @categories = current_user.categories
  end

  def transaction_processor
    @transaction_processor ||= Transactions::ProcessorService.new(@transaction)
  end
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, class: "max-w-xl mx-auto p-6 bg-white rounded-lg shadow-lg space-y-6") do |form| %>
  <h1 class="text-2xl font-semibold text-gray-900 mb-4 text-center "><%= form_title %></h1>
  <% if transaction.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-5" role="alert">
      <ul class="mt-2">
        <% transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="grid grid-cols-1 gap-6">
    <div>
      <%= form.label :description, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :description, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>
    <div>
      <%= form.label :amount, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :amount, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>
    <div>
      <%= form.label :transaction_type, class: "block text-sm font-medium text-gray-700" %>
      <%= form.select :transaction_type, Transaction.transaction_types.keys.map { |type| [t("activerecord.attributes.transaction.transaction_types.#{type}"), type] }, { include_blank: t("transactions.actions.select") }, { class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" } %>
    </div>
    <div>
      <%= form.label :due_date, class: "block text-sm font-medium text-gray-700" %>
      <%= form.date_field :due_date, value: Date.current.to_s, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>
    <div>
      <%= form.label :account_id, class: "block text-sm font-medium text-gray-700" %>
      <%= form.select :account_id, current_user.accounts.map { |account| [account.name, account.id]}, { include_blank: t("transactions.actions.select") }, {class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" } %>
    </div>
    <div>
      <%= form.label :category_id, class: "block text-sm font-medium text-gray-700" %>
      <%= form.select :category_id, current_user.categories.map { |category| [category.name, category.id]}, { include_blank: t("transactions.actions.select") }, {class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" } %>
    </div>
    <div>
      <%= form.label :status, class: "block text-sm font-medium text-gray-700" %>
      <%= form.select :status, Transaction.statuses.keys.map { |status| [t("activerecord.attributes.transaction.statuses.#{status}"), status] }, { include_blank: t("transactions.actions.select") }, { class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" } %>
    </div>
    <div>
      <%= form.label :voucher, class: "block text-sm font-medium text-gray-700" %>
      <%= form.file_field :voucher, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100" %>
    </div>
  </div>
  <div class="mt-6 flex justify-end">
    <%= form.submit t("actions.save"), class: "inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
  </div>
<% end %>

app/views/transactions/_search_form.html.erb
<div class="mb-4">
  <details class="border border-gray-300 rounded-md">
    <summary class="cursor-pointer bg-gray-100 px-4 py-2 text-base font-medium text-gray-700 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2">
      <%= I18n.t("transactions.actions.show_filters") %>
    </summary>
    <div class="mt-4 px-4 py-2">
      <%= search_form_for @q, url: transactions_path, method: :get, local: true, class: "space-y-4" do |f| %>
        <table class="w-full">
          <thead>
            <tr>
              <th class="text-left text-sm font-medium text-gray-700"><%= f.label :description %></th>
              <th class="text-left text-sm font-medium text-gray-700"><%= f.label :transaction_type %></th>
              <th class="text-left text-sm font-medium text-gray-700"><%= f.label :due_date_gteq, "Data Venc. Inicial" %></th>
              <th class="text-left text-sm font-medium text-gray-700"><%= f.label :due_date_lteq, "Data Venc. Final" %></th>
              <th class="text-left text-sm font-medium text-gray-700"><%= f.label :account_id %></th>
              <th class="text-left text-sm font-medium text-gray-700"><%= f.label :category_id %></th>
              <th class="text-left text-sm font-medium text-gray-700"><%= f.label :status %></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <%= f.search_field :description_cont, class: "mt-1 block w-full sm:w-32 shadow-sm sm:text-sm border-gray-300 rounded-md" %>
              </td>
              <td>
                <%= f.select :transaction_type_eq, options_for_select(Transaction.transaction_types.map { |key, _value| [t("activerecord.attributes.transaction.transaction_types.#{key}"), key] }), { include_blank: t("transactions.actions.select") }, class: "mt-1 block w-full sm:w-32 shadow-sm sm:text-sm border-gray-300 rounded-md" %>
              </td>
              <td>
                <%= f.date_field :due_date_gteq, class: "mt-1 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
              </td>
              <td>
                <%= f.date_field :due_date_lteq, class: "mt-1 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
              </td>
              <td>
                <%= f.select :account_id, options_for_select(@accounts.map { |account| [account.name, account.id] }), { include_blank: t("transactions.actions.select") }, class: "mt-1 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
              </td>
              <td>
                <%= f.select :category_id_eq, options_for_select(@categories.map { |category| [category.name, category.id] }), { include_blank: t("transactions.actions.select") }, class: "mt-1 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
              </td>
              <td>
                <%= f.select :status_eq, options_for_select(Transaction.statuses.map { |key, _value| [t("activerecord.attributes.transaction.statuses.#{key}"), key] }), { include_blank: t("transactions.actions.select") }, class: "mt-1 block w-full sm:w-32 shadow-sm sm:text-sm border-gray-300 rounded-md" %>
              </td>
            </tr>
          </tbody>
        </table>
        <div class="flex justify-start mt-4 space-x-4">
          <%= f.submit t("transactions.actions.filter"), class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
          <%= link_to t("transactions.actions.clear"), transactions_path, class: "inline-flex items-center justify-center rounded-md border border-gray-300 bg-gray-100 px-4 py-2 text-base font-medium text-gray-700 shadow-sm hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2" %>
        </div>
      <% end %>
    </div>
  </details>
</div>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>" class="bg-white shadow overflow-hidden sm:rounded-lg">
  <div class="px-4 py-5 sm:px-6">
    <h3 class="text-lg leading-6 font-medium text-gray-900">
      <%= I18n.t("views.transaction.actions.details")%> - <%= transaction.description%>
    </h3>
  </div>
  <div class="border-t border-gray-200">
    <dl>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          <%= I18n.t("attributes.amount") %>
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= transaction.amount %>
        </dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          <%= I18n.t("attributes.transaction_type") %>
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= I18n.t("activerecord.attributes.transaction_types.#{transaction.transaction_type}") %>
        </dd>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          <%= I18n.t("attributes.description") %>
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= transaction.description %>
        </dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          <%= I18n.t("attributes.due_date") %>
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= transaction.due_date.strftime("%d/%m/%Y") %>
        </dd>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          <%= I18n.t("attributes.account_id") %>
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= transaction.account.name %>
        </dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          <%= I18n.t("attributes.category_id") %>
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= transaction.category.name %>
        </dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          <%= I18n.t("attributes.status") %>
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= I18n.t("activerecord.attributes.statuses.#{transaction.status}") %>
        </dd>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          <%= I18n.t("attributes.voucher") %>
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= link_to image_tag(transaction.voucher, class: "max-w-xs max-h-48"), transaction.voucher if transaction.voucher.attached? %>
        </dd>
      </div>
    </dl>
  </div>
</div>

app/views/transactions/edit.html.erb
<% content_for(:page_title, I18n.t("models.transactions")) %>
<%= render "form", transaction: @transaction, form_title: I18n.t("transactions.actions.edit") %>
<div class="mt-6 flex justify-center space-x-4">
  <%= link_to I18n.t("actions.back"), transactions_path, class: "inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"  %>
  <%= button_to I18n.t("actions.destroy"), @transaction, method: :delete, data: { confirm: "Are you sure?" }, class: "inline-flex items-center px-4 py-2 border border-red-300 rounded-md shadow-sm text-sm font-medium text-red-700 bg-white hover:bg-red-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500" %>
</div>

app/views/transactions/index.html.erb
<% content_for(:page_title, I18n.t("models.transactions")) %>
<div class="flex justify-end mb-4">
  <%= link_to I18n.t("transactions.actions.new"), new_transaction_path, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
</div>
<%= render "search_form" %>
<div class="overflow-x-auto relative shadow-lg sm:rounded-lg">
  <table class="w-full text-sm text-left text-gray-500">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50">
      <tr>
        <th scope="col" class="py-3 px-6 text-center"><%= sort_link(@q, :description) %></th>
        <th scope="col" class="py-3 px-6 text-center"><%= sort_link(@q, :amount) %></th>
        <th scope="col" class="py-3 px-6 text-center"><%= sort_link(@q, :transaction_type) %></th>
        <th scope="col" class="py-3 px-6 text-center"><%= sort_link(@q, :due_date) %></th>
        <th scope="col" class="py-3 px-6 text-center"><%= sort_link(@q, :account_id) %></th>
        <th scope="col" class="py-3 px-6 text-center"><%= sort_link(@q, :category_id) %></th>
        <th scope="col" class="py-3 px-6 text-center"><%= sort_link(@q, :status) %></th>
        <th scope="col" class="py-3 px-6 text-center"><%= t("helpers.table.actions") %></th>
      </tr>
    </thead>
    <tbody class="bg-white">
      <% @transactions.each_with_index do |transaction, index| %>
        <tr class="<%= index.odd? ? 'bg-gray-50' : 'bg-white' %> hover:bg-gray-100">
          <td class="py-3 px-6 text-center align-middle"><%= transaction.description %></td>
          <td class="py-3 px-6 text-center align-middle"><%= transaction.amount %></td>
          <td class="py-3 px-6 text-center align-middle"><%= t("activerecord.attributes.transaction.transaction_types.#{transaction.transaction_type}") %></td>
          <td class="py-3 px-6 text-center align-middle"><%= transaction.due_date.strftime('%d/%m/%Y') %></td>
          <td class="py-3 px-6 text-center align-middle"><%= transaction.account.name %></td>
          <td class="py-3 px-6 text-center align-middle"><%= transaction.category.name %></td>
          <td class="py-3 px-6 text-center align-middle"><%= t("activerecord.attributes.transaction.statuses.#{transaction.status}") %></td>
          <td class="py-4 px-6 text-center align-middle">
            <div class="flex justify-center space-x-4">
              <%= link_to I18n.t("actions.show"), transaction_path(transaction), class: "text-green-600 hover:text-green-700" %>
              <%= link_to I18n.t("actions.edit"), edit_transaction_path(transaction), class: "text-blue-600 hover:text-blue-700" %>
              <%= button_to I18n.t("actions.destroy"), transaction_path(transaction), method: :delete, data: { confirm: "Are you sure?" }, class: "text-red-600 hover:text-red-700" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/transactions/new.html.erb
<% content_for(:page_title, I18n.t("models.transactions")) %>
<%= render "form", transaction: @transaction, form_title: I18n.t("transactions.actions.new") %>
<div class="mt-6 flex justify-center">
  <%= link_to I18n.t("actions.back"), transactions_path, class: "inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
</div>

app/views/transactions/show.html.erb
<% content_for(:page_title, I18n.t("models.transactions")) %>
<%= render @transaction %>
<div class="flex justify-center mt-4 space-x-4">
  <%= link_to I18n.t("actions.back"), transactions_path, class: "inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  <%= link_to I18n.t("actions.edit"), edit_transaction_path(@transaction), class: "inline-flex items-center px-4 py-2 border border-blue-300 rounded-md shadow-sm text-sm font-medium text-blue-700 bg-white hover:bg-blue-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
  <%= button_to I18n.t("actions.destroy"), @transaction, method: :delete, data: { confirm: "Are you sure?" }, class: "inline-flex items-center px-4 py-2 border border-red-300 rounded-md shadow-sm text-sm font-medium text-red-700 bg-white hover:bg-red-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500" %>
</div>