config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :accounts
  resources :categories
  resources :transactions
  resources :goals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  include DefaultUuid

  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :balance, numericality: { greater_than_or_equal_to: 0 }

  before_validation :set_default_balance

  def partial_balance
    transactions.income.sum(:amount) - transactions.expense.sum(:amount)
  end

  def update_balance
    Accounts::UpdateBalanceService.new(@transaction.account).call
  end

  private

  def set_default_balance
    self.balance ||= 0
  end
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: %i[show edit update destroy]

  def index
    @accounts = current_user.accounts.order(:created_at)
  end

  def show; end

  def new
    @account = Account.new
  end

  def edit; end

  def create
    @account = current_user.accounts.new(account_params)

    if @account.save
      redirect_to accounts_path, notice: t("views.account.notice.create")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @account.update(account_params)
      redirect_to accounts_path, notice: t("views.account.notice.edit"), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @account.destroy!
    redirect_to accounts_url, notice: t("views.account.notice.destroy"), status: :see_other
  end

  private

  def set_account
    @account = Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:name, :balance)
  end
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <p>
    <strong>Name:</strong>
    <%= account.name %>
  </p>
  <p>
    <strong>Balance:</strong>
    <%= account.balance %>
  </p>
</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account, class: "max-w-xl mx-auto p-6 bg-white rounded-lg shadow-lg space-y-6") do |form| %>
  <h1 class="text-2xl font-semibold text-gray-900 mb-4 text-center "><%= form_title %></h1>
  <% if account.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-5" role="alert">
      <ul class="mt-2">
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="grid grid-cols-1 gap-6">
    <div>
      <%= form.label :name, I18n.t("activerecord.attributes.name"), class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :name, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>
    <div>
      <%= form.label :balance, I18n.t("activerecord.attributes.balance"), class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :balance, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50", disabled: true %>
    </div>
  </div>
  <div class="mt-6 flex justify-end">
    <%= form.submit I18n.t("actions.save"), class: "inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<% content_for(:page_title, I18n.t("models.accounts")) %>
<%= render "form", account: @account, form_title: I18n.t("views.account.actions.edit") %>
<div class="mt-6 flex justify-center space-x-4">
  <%= link_to I18n.t("actions.back"), accounts_path, class: "inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  <%= button_to I18n.t("actions.destroy"), @account, method: :delete, data: { confirm: "Are you sure?" }, class: "inline-flex items-center px-4 py-2 border border-red-300 rounded-md shadow-sm text-sm font-medium text-red-700 bg-white hover:bg-red-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500" %>
</div>

app/views/accounts/index.html.erb
<% content_for(:page_title, I18n.t("activerecord.model.accounts")) %>
<div class="bg-white py-24 sm:py-32">
  <div class="mx-auto max-w-7xl px-6 lg:px-8">
    <div class="mx-auto max-w-2xl lg:text-center">
      <p class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl"><%= t("views.account.messages.title") %></p>
      <p class="mt-6 text-lg leading-8 text-gray-600"><%= t("views.account.messages.paragraph") %></p>
    </div>
    <div class="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-4xl ">
      <dl class="grid max-w-xl grid-cols-1 gap-x-8 gap-y-10 lg:max-w-none lg:grid-cols-2 lg:gap-y-16">
        <% @accounts.each do |account| %>
          <div class="relative pl-16">
            <dt class="text-base font-semibold leading-7 text-gray-900">
              <%= link_to edit_account_path(account), class: "absolute left-0 top-0 flex h-10 w-10 items-center justify-center rounded-lg bg-indigo-600" do %>
                <svg class="h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M12 21v-8.25M15.75 21v-8.25M8.25 21v-8.25M3 9l9-6 9 6m-1.5 12V10.332A48.36 48.36 0 0 0 12 9.75c-2.551 0-5.056.2-7.5.582V21M3 21h18M12 6.75h.008v.008H12V6.75Z" />
                </svg>
              <% end %>
              <%= account.name %>
            </dt>
            <dd class="mt-2 text-base leading-7 text-gray-600">
              <p><strong><%= I18n.t("activerecord.attributes.balance") %>:</strong> <span class="text-lg font-bold text-indigo-700"><%= format_currency(account.balance) %></span></p>
              <p><strong><%= I18n.t("activerecord.attributes.partial_balance") %>:</strong> <span class="text-lg font-bold text-indigo-700"><%= format_currency(account.partial_balance) %></span></p>
              <p class="text-sm leading-5 pt-2">
                <%= link_to edit_account_path(account), class: "flex items-center text-indigo-500 hover:text-indigo-900" do %>
                  <%= I18n.t("views.account.actions.editing")%>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3 ml-1">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3" />
                  </svg>
                <% end %>
              </p>
              <p class="text-sm leading-5 pt-2">
                <%= link_to new_transaction_path(account_id: account.id, transaction_type: 'income'), class: "flex items-center text-green-700 hover:text-green-900" do %>
                  <%= I18n.t("views.account.actions.add_income") %>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3 ml-1">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                  </svg>
                <% end %>
              </p>
              <p class="text-sm leading-5 pt-2">
                <%= link_to new_transaction_path(account_id: account.id, transaction_type: 'expense'), class: "flex items-center text-red-700 hover:text-red-900" do %>
                  <%= I18n.t("views.account.actions.add_expense") %>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3 ml-1">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15" />
                  </svg>
                <% end %>
              </p>
            </dd>
          </div>
        <% end %>
      </dl>
    </div>
    <div class="mx-auto mt-8 max-w-2xl lg:mt-12 lg:max-w-4xl lg:text-center">
      <%= link_to I18n.t("views.account.actions.new"), new_account_path, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
    </div>
  </div>
</div>

app/views/accounts/new.html.erb
<% content_for(:page_title, I18n.t("models.accounts")) %>
<%= render "form", account: @account, form_title: I18n.t("views.account.actions.new") %>
<div class="mt-6 flex justify-center">
  <%= link_to I18n.t("actions.back"), accounts_path, class: "inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
</div>

app/views/accounts/show.html.erb
<% content_for(:page_title, "Accounts") %>
<p style="color: green"><%= notice %></p>
<%= render @account %>
<div>
  <%= link_to "Edit this account", edit_account_path(@account) %> |
  <%= link_to "Back to accounts", accounts_path %>
  <%= button_to "Destroy this account", @account, method: :delete %>
</div>